# Simple Fault Alert
# Notifies immediately when any fault code is detected
#
# Requirements:
# - sensor.srne_inverter_fault_code (Fault code sensor)
#
# Usage:
# 1. Copy this file to your config/automations directory
# 2. Adjust notification service if needed
# 3. Optionally add more actions (email, SMS, etc.)

automation:
  - alias: "SRNE: Fault Code Alert"
    description: "Immediate notification on any fault detection"

    trigger:
      - platform: state
        entity_id: sensor.srne_inverter_fault_code

    condition:
      - condition: template
        value_template: "{{ trigger.to_state.state not in ['0', 'unknown', 'unavailable'] }}"

    action:
      - service: notify.notify
        data:
          title: "SRNE Inverter Fault!"
          message: >
            Fault Code: {{ states('sensor.srne_inverter_fault_code') }}
            Status: {{ state_attr('sensor.srne_inverter_fault_code', 'friendly_name') }}
            Time: {{ now().strftime('%Y-%m-%d %H:%M:%S') }}
          data:
            priority: high
            tag: "inverter_fault"
